-- schema.sql
-- Behavioral Funnel Agent — database schema (PostgreSQL 14+)
--
-- Design rules honored here:
--   * Every DATA table carries a site_id (prototype constant 'default'),
--     so nothing blocks multi-tenant later. A `sites` parent table anchors it.
--   * NO business rules live in the schema. Funnel logic, thresholds,
--     page-type mappings, templates and guardrail params live in config
--     files (primary) or the optional `site_config` DB rows (per-site override).
--   * Timestamps are TIMESTAMPTZ. JSON payloads are JSONB.
--
-- Idempotent: safe to run repeatedly (IF NOT EXISTS / ON CONFLICT).

-- ---------------------------------------------------------------------------
-- Tenant anchor
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sites (
    site_id    TEXT PRIMARY KEY,
    name       TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Seed the single prototype tenant.
INSERT INTO sites (site_id, name)
VALUES ('default', 'Default Site')
ON CONFLICT (site_id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Leads (a known person) + consent + latest scoring snapshot
--   Written by: /identify (Layer 1), scoring (Layer 2).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS leads (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id           TEXT NOT NULL DEFAULT 'default' REFERENCES sites(site_id),

    -- identity
    name              TEXT,
    email             TEXT,
    phone             TEXT,

    -- consent (captured at /identify)
    email_opt_in      BOOLEAN     NOT NULL DEFAULT FALSE,
    whatsapp_opt_in   BOOLEAN     NOT NULL DEFAULT FALSE,
    consent_timestamp TIMESTAMPTZ,
    consent_source    TEXT,

    -- latest scoring snapshot (Layer 2, Stage B output)
    funnel_stage      TEXT,                                   -- TOFU | MOFU | BOFU (values from config)
    intent_score      INTEGER CHECK (intent_score IS NULL OR intent_score BETWEEN 0 AND 100),
    likely_objections JSONB   NOT NULL DEFAULT '[]'::jsonb,   -- array of strings
    persona_signals   JSONB   NOT NULL DEFAULT '{}'::jsonb,   -- object
    scored_at         TIMESTAMPTZ,
    scoring_error     TEXT,                                   -- set when Stage B failed after retry (flag)

    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Backfill on pre-existing deployments (idempotent).
ALTER TABLE leads ADD COLUMN IF NOT EXISTS name TEXT;

-- One lead per email/phone within a site (case-insensitive email).
CREATE UNIQUE INDEX IF NOT EXISTS leads_site_email_uniq
    ON leads (site_id, lower(email)) WHERE email IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS leads_site_phone_uniq
    ON leads (site_id, phone) WHERE phone IS NOT NULL;

-- Lookups compare digits only ('+91 96995 30806' from a form is the same person
-- as '919699530806' from WhatsApp), so the match needs its own expression index
-- or every /identify and every inbound message scans the whole table.
-- Deliberately NOT unique: existing rows may already hold digit-variant
-- duplicates, and a failed index build would block startup.
CREATE INDEX IF NOT EXISTS leads_site_phone_digits_idx
    ON leads (site_id, (regexp_replace(phone, '\D', '', 'g'))) WHERE phone IS NOT NULL;

-- Added after v1: idempotent for databases created before scoring_error existed.
ALTER TABLE leads ADD COLUMN IF NOT EXISTS scoring_error TEXT;

-- Stage provenance: which rule (or the model) set funnel_stage, and the evidence
-- behind it — so every stage on the dashboard can be explained, not just asserted.
ALTER TABLE leads ADD COLUMN IF NOT EXISTS stage_source TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS stage_reason TEXT;

-- Proof of ownership, not permission. A phone that passed an OTP check is a very
-- different thing from one typed into a form: it is known to belong to the person
-- holding the handset. It still says nothing about whether they agreed to be
-- messaged — that stays in whatsapp_opt_in / email_opt_in.
ALTER TABLE leads ADD COLUMN IF NOT EXISTS phone_verified    BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS phone_verified_at TIMESTAMPTZ;

-- When the welcome message was sent. Its only job is idempotency: identify runs
-- again on every correction and re-verification, and nobody should be welcomed
-- twice because they fixed a typo in their number.
ALTER TABLE leads ADD COLUMN IF NOT EXISTS welcomed_at TIMESTAMPTZ;

-- ---------------------------------------------------------------------------
-- Identities: maps an anonymous_id (browser/device) to a lead once known.
--   A lead may accumulate several anonymous_ids over time (multi-device).
--   Written by: /track (creates unlinked row), /identify (sets lead_id).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS identities (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id       TEXT NOT NULL DEFAULT 'default' REFERENCES sites(site_id),
    anonymous_id  TEXT NOT NULL,
    lead_id       BIGINT REFERENCES leads(id) ON DELETE SET NULL,
    -- approximate geo, resolved once from the visitor's IP (raw IP is NOT stored);
    -- timezone comes from the browser instantly as a fallback hint.
    country       TEXT,
    region        TEXT,
    city          TEXT,
    timezone      TEXT,
    latitude      DOUBLE PRECISION,
    longitude     DOUBLE PRECISION,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (site_id, anonymous_id)
);
-- Backfill columns on pre-existing deployments (idempotent).
ALTER TABLE identities ADD COLUMN IF NOT EXISTS country   TEXT;
ALTER TABLE identities ADD COLUMN IF NOT EXISTS region    TEXT;
ALTER TABLE identities ADD COLUMN IF NOT EXISTS city      TEXT;
ALTER TABLE identities ADD COLUMN IF NOT EXISTS timezone  TEXT;
ALTER TABLE identities ADD COLUMN IF NOT EXISTS latitude  DOUBLE PRECISION;
ALTER TABLE identities ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

-- Finer location detail. `district` is the neighbourhood/locality inside a city
-- ("Koregaon Park"), `street` the road. Both are only trustworthy when
-- location_source = 'gps': an IP resolves to the ISP's gateway, which for mobile
-- carriers can be a different city entirely, so accuracy_m stays NULL there and
-- the UI labels it approximate.
ALTER TABLE identities ADD COLUMN IF NOT EXISTS district        TEXT;
ALTER TABLE identities ADD COLUMN IF NOT EXISTS street          TEXT;
ALTER TABLE identities ADD COLUMN IF NOT EXISTS postal          TEXT;
ALTER TABLE identities ADD COLUMN IF NOT EXISTS isp             TEXT;
ALTER TABLE identities ADD COLUMN IF NOT EXISTS accuracy_m      INTEGER;   -- GPS only
ALTER TABLE identities ADD COLUMN IF NOT EXISTS location_source TEXT;      -- 'ip' | 'gps'
ALTER TABLE identities ADD COLUMN IF NOT EXISTS located_at      TIMESTAMPTZ;

-- The browser's own description of itself, taken from the request header once
-- per visitor. Crawlers announce themselves here, and it is the only reliable
-- way to tell Meta's link crawler from a person: it runs JavaScript, so it
-- accumulates dwell time and fires clicks exactly like a real visit.
ALTER TABLE identities ADD COLUMN IF NOT EXISTS user_agent TEXT;
CREATE INDEX IF NOT EXISTS identities_site_lead_idx ON identities (site_id, lead_id);

-- ---------------------------------------------------------------------------
-- Events: raw behavioral stream.
--   lead_id is NULL until /identify backfills prior events for the anonymous_id.
--   page_type is resolved from config at ingest (recomputable if config changes).
--   Written by: /track (Layer 1). Read by: scoring Stage A (Layer 2).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id      TEXT NOT NULL DEFAULT 'default' REFERENCES sites(site_id),
    anonymous_id TEXT NOT NULL,
    lead_id      BIGINT REFERENCES leads(id) ON DELETE SET NULL,  -- backfilled on identify

    event_type   TEXT NOT NULL,                          -- page_view, checkout_start, ... (from client)
    url          TEXT,
    page_type    TEXT,                                   -- blog | pricing | ... (resolved from config)
    session_id   TEXT,
    metadata     JSONB NOT NULL DEFAULT '{}'::jsonb,

    occurred_at  TIMESTAMPTZ NOT NULL,                   -- client event time
    received_at  TIMESTAMPTZ NOT NULL DEFAULT now(),     -- server ingest time
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS events_site_anon_idx ON events (site_id, anonymous_id);
CREATE INDEX IF NOT EXISTS events_site_lead_idx ON events (site_id, lead_id);
CREATE INDEX IF NOT EXISTS events_site_time_idx ON events (site_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS events_site_type_idx ON events (site_id, event_type);

-- ---------------------------------------------------------------------------
-- Decisions: EVERY decision proposed by the engine is logged — including the
--   ones guardrails reject — with the full model reasoning and raw JSON.
--   Written by: decision engine + guardrails (Layer 3).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS decisions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id          TEXT   NOT NULL DEFAULT 'default' REFERENCES sites(site_id),
    lead_id          BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,

    action           TEXT NOT NULL,                       -- send_email | send_whatsapp | wait | handoff_human
    channel          TEXT,                                -- email | whatsapp | NULL
    message          TEXT,
    send_at          TIMESTAMPTZ,
    reasoning        TEXT,

    status           TEXT  NOT NULL DEFAULT 'proposed',   -- proposed | accepted | rejected
    guardrail_result JSONB NOT NULL DEFAULT '{}'::jsonb,  -- {passed: bool, violations: [...]}
    model            TEXT,                                -- model id that produced the decision
    raw_response     JSONB,                               -- full model JSON, for audit

    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS decisions_site_lead_idx ON decisions (site_id, lead_id, created_at DESC);
CREATE INDEX IF NOT EXISTS decisions_site_time_idx ON decisions (site_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- Sent messages: the STUBBED execution log. Nothing is transmitted.
--   status='skipped' + skip_reason records consent re-checks that blocked a send.
--   sender_type names the stub so a real provider can drop in later.
--   Written by: execution senders (Layer 4).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sent_messages (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id     TEXT   NOT NULL DEFAULT 'default' REFERENCES sites(site_id),
    lead_id     BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    decision_id BIGINT REFERENCES decisions(id) ON DELETE SET NULL,

    channel     TEXT NOT NULL,                            -- email | whatsapp
    sender_type TEXT NOT NULL,                            -- stub_email | stub_whatsapp
    to_address  TEXT,                                     -- email or phone the send targeted
    message     TEXT NOT NULL,
    metadata    JSONB NOT NULL DEFAULT '{}'::jsonb,

    status      TEXT NOT NULL,                            -- sent | skipped
    skip_reason TEXT,                                     -- e.g. consent_revoked, opt_out (when skipped)

    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS sent_site_lead_idx ON sent_messages (site_id, lead_id, created_at DESC);
CREATE INDEX IF NOT EXISTS sent_site_time_idx ON sent_messages (site_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- Conversations: one thread per (channel, contact address).
--
--   Keyed on the ADDRESS, not the lead: an inbound WhatsApp message arrives from
--   a phone number before we know who it belongs to, so the thread must exist
--   first and get attached to a lead once identified.
--
--   window_expires_at encodes WhatsApp's 24-hour customer-service window: free
--   text may only be sent within 24h of the contact's own last message; outside
--   it, Meta requires an approved template. It is per-conversation state (it
--   moves every time they message you), which is why it cannot live in config.
--   Written by: messaging service (inbound webhook + outbound sends).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS conversations (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id           TEXT   NOT NULL DEFAULT 'default' REFERENCES sites(site_id),
    lead_id           BIGINT REFERENCES leads(id) ON DELETE SET NULL,

    channel           TEXT NOT NULL,                        -- whatsapp | email
    contact           TEXT NOT NULL,                        -- phone (digits) or email address

    status            TEXT NOT NULL DEFAULT 'open',         -- open | closed
    unread_count      INTEGER NOT NULL DEFAULT 0,           -- inbound messages not yet read in the dashboard

    last_message_at   TIMESTAMPTZ,
    last_inbound_at   TIMESTAMPTZ,
    last_outbound_at  TIMESTAMPTZ,
    window_expires_at TIMESTAMPTZ,                          -- last_inbound_at + 24h (WhatsApp)

    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (site_id, channel, contact)
);
CREATE INDEX IF NOT EXISTS conversations_site_recent_idx ON conversations (site_id, last_message_at DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS conversations_site_lead_idx   ON conversations (site_id, lead_id);

-- ---------------------------------------------------------------------------
-- Messages: the conversation itself, both directions.
--
--   Distinct from `sent_messages`, which stays the audit trail of what the AGENT
--   decided to send and what happened to that decision. This table is the thread
--   a human reads: inbound replies, outbound sends, and delivery state.
--   provider_message_id is unique per site so provider webhook retries (Meta
--   redelivers until it gets a 200) can never duplicate a row.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS messages (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id             TEXT   NOT NULL DEFAULT 'default' REFERENCES sites(site_id),
    conversation_id     BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    lead_id             BIGINT REFERENCES leads(id) ON DELETE SET NULL,

    direction           TEXT NOT NULL,                      -- in | out
    channel             TEXT NOT NULL,
    body                TEXT,
    message_type        TEXT NOT NULL DEFAULT 'text',       -- text | template | image | audio | document | ...
    media               JSONB NOT NULL DEFAULT '{}'::jsonb, -- provider media ids/urls when not text

    -- outbound lifecycle: queued -> sent -> delivered -> read (or failed)
    -- inbound is always 'received'
    status              TEXT NOT NULL DEFAULT 'queued',
    error               TEXT,
    provider_message_id TEXT,
    sender_type         TEXT,                               -- which Sender produced it
    decision_id         BIGINT REFERENCES decisions(id) ON DELETE SET NULL,
    sent_message_id     BIGINT REFERENCES sent_messages(id) ON DELETE SET NULL,

    occurred_at         TIMESTAMPTZ NOT NULL DEFAULT now(), -- provider timestamp when supplied
    delivered_at        TIMESTAMPTZ,
    read_at             TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS messages_conversation_idx ON messages (conversation_id, occurred_at ASC, id ASC);
CREATE INDEX IF NOT EXISTS messages_site_lead_idx    ON messages (site_id, lead_id);
CREATE UNIQUE INDEX IF NOT EXISTS messages_provider_id_uniq
    ON messages (site_id, provider_message_id) WHERE provider_message_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- pending_receipts — delivery receipts that arrived before their message row
--   had a provider id.
--
--   Meta returns the message id in its API response and can deliver the 'sent'
--   webhook a moment later; if that webhook wins the race, the receipt has
--   nothing to match on and the message would be stuck showing 'sent' forever.
--   Unmatched receipts are parked here and applied when the id is attached.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pending_receipts (
    site_id             TEXT NOT NULL DEFAULT 'default' REFERENCES sites(site_id),
    provider_message_id TEXT NOT NULL,
    status              TEXT NOT NULL,
    error               TEXT,
    occurred_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (site_id, provider_message_id)
);

-- ---------------------------------------------------------------------------
-- visitor_presence — one row per visitor, updated on every heartbeat/page view.
--   Powers the dashboard "Live now" panel. Kept OUT of the events table so
--   frequent heartbeats never bloat event history or skew scoring.
--   Written by: Layer 1 ingest (upsert). Read by: dashboard /api/live.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS visitor_presence (
    site_id       TEXT NOT NULL DEFAULT 'default' REFERENCES sites(site_id),
    anonymous_id  TEXT NOT NULL,
    session_id    TEXT,
    url           TEXT,
    page_type     TEXT,
    last_seen_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (site_id, anonymous_id)
);
CREATE INDEX IF NOT EXISTS visitor_presence_seen_idx ON visitor_presence (site_id, last_seen_at DESC);

-- ---------------------------------------------------------------------------
-- Optional per-site config overrides (DB-row form of the file config).
--   Files under /config are the source of truth for the prototype; rows here,
--   when present, override file defaults for a given site — the multi-tenant path.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS site_config (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    TEXT NOT NULL DEFAULT 'default' REFERENCES sites(site_id),
    key        TEXT NOT NULL,                             -- page_types | scoring | guardrails | templates
    value      JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (site_id, key)
);

-- ---------------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS leads_set_updated_at ON leads;
CREATE TRIGGER leads_set_updated_at
    BEFORE UPDATE ON leads
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS site_config_set_updated_at ON site_config;
CREATE TRIGGER site_config_set_updated_at
    BEFORE UPDATE ON site_config
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS conversations_set_updated_at ON conversations;
CREATE TRIGGER conversations_set_updated_at
    BEFORE UPDATE ON conversations
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
