-- schema.sql
-- Behavioral Funnel Agent — database schema (PostgreSQL 14+)
--
-- Design rules honored here:
--   * Every DATA table carries a site_id (prototype constant 'default'),
--     so nothing blocks multi-tenant later. A `sites` parent table anchors it.
--   * NO business rules live in the schema. Funnel logic, thresholds,
--     page-type mappings, templates and guardrail params live in config
--     files (primary) or the optional `site_config` DB rows (per-site override).
--   * Timestamps are TIMESTAMPTZ. JSON payloads are JSONB.
--
-- Idempotent: safe to run repeatedly (IF NOT EXISTS / ON CONFLICT).

-- ---------------------------------------------------------------------------
-- Tenant anchor
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sites (
    site_id    TEXT PRIMARY KEY,
    name       TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Seed the single prototype tenant.
INSERT INTO sites (site_id, name)
VALUES ('default', 'Default Site')
ON CONFLICT (site_id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Leads (a known person) + consent + latest scoring snapshot
--   Written by: /identify (Layer 1), scoring (Layer 2).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS leads (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id           TEXT NOT NULL DEFAULT 'default' REFERENCES sites(site_id),

    -- identity
    email             TEXT,
    phone             TEXT,

    -- consent (captured at /identify)
    email_opt_in      BOOLEAN     NOT NULL DEFAULT FALSE,
    whatsapp_opt_in   BOOLEAN     NOT NULL DEFAULT FALSE,
    consent_timestamp TIMESTAMPTZ,
    consent_source    TEXT,

    -- latest scoring snapshot (Layer 2, Stage B output)
    funnel_stage      TEXT,                                   -- TOFU | MOFU | BOFU (values from config)
    intent_score      INTEGER CHECK (intent_score IS NULL OR intent_score BETWEEN 0 AND 100),
    likely_objections JSONB   NOT NULL DEFAULT '[]'::jsonb,   -- array of strings
    persona_signals   JSONB   NOT NULL DEFAULT '{}'::jsonb,   -- object
    scored_at         TIMESTAMPTZ,
    scoring_error     TEXT,                                   -- set when Stage B failed after retry (flag)

    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One lead per email/phone within a site (case-insensitive email).
CREATE UNIQUE INDEX IF NOT EXISTS leads_site_email_uniq
    ON leads (site_id, lower(email)) WHERE email IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS leads_site_phone_uniq
    ON leads (site_id, phone) WHERE phone IS NOT NULL;

-- Added after v1: idempotent for databases created before scoring_error existed.
ALTER TABLE leads ADD COLUMN IF NOT EXISTS scoring_error TEXT;

-- ---------------------------------------------------------------------------
-- Identities: maps an anonymous_id (browser/device) to a lead once known.
--   A lead may accumulate several anonymous_ids over time (multi-device).
--   Written by: /track (creates unlinked row), /identify (sets lead_id).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS identities (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id       TEXT NOT NULL DEFAULT 'default' REFERENCES sites(site_id),
    anonymous_id  TEXT NOT NULL,
    lead_id       BIGINT REFERENCES leads(id) ON DELETE SET NULL,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (site_id, anonymous_id)
);
CREATE INDEX IF NOT EXISTS identities_site_lead_idx ON identities (site_id, lead_id);

-- ---------------------------------------------------------------------------
-- Events: raw behavioral stream.
--   lead_id is NULL until /identify backfills prior events for the anonymous_id.
--   page_type is resolved from config at ingest (recomputable if config changes).
--   Written by: /track (Layer 1). Read by: scoring Stage A (Layer 2).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id      TEXT NOT NULL DEFAULT 'default' REFERENCES sites(site_id),
    anonymous_id TEXT NOT NULL,
    lead_id      BIGINT REFERENCES leads(id) ON DELETE SET NULL,  -- backfilled on identify

    event_type   TEXT NOT NULL,                          -- page_view, checkout_start, ... (from client)
    url          TEXT,
    page_type    TEXT,                                   -- blog | pricing | ... (resolved from config)
    session_id   TEXT,
    metadata     JSONB NOT NULL DEFAULT '{}'::jsonb,

    occurred_at  TIMESTAMPTZ NOT NULL,                   -- client event time
    received_at  TIMESTAMPTZ NOT NULL DEFAULT now(),     -- server ingest time
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS events_site_anon_idx ON events (site_id, anonymous_id);
CREATE INDEX IF NOT EXISTS events_site_lead_idx ON events (site_id, lead_id);
CREATE INDEX IF NOT EXISTS events_site_time_idx ON events (site_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS events_site_type_idx ON events (site_id, event_type);

-- ---------------------------------------------------------------------------
-- Decisions: EVERY decision proposed by the engine is logged — including the
--   ones guardrails reject — with the full model reasoning and raw JSON.
--   Written by: decision engine + guardrails (Layer 3).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS decisions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id          TEXT   NOT NULL DEFAULT 'default' REFERENCES sites(site_id),
    lead_id          BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,

    action           TEXT NOT NULL,                       -- send_email | send_whatsapp | wait | handoff_human
    channel          TEXT,                                -- email | whatsapp | NULL
    message          TEXT,
    send_at          TIMESTAMPTZ,
    reasoning        TEXT,

    status           TEXT  NOT NULL DEFAULT 'proposed',   -- proposed | accepted | rejected
    guardrail_result JSONB NOT NULL DEFAULT '{}'::jsonb,  -- {passed: bool, violations: [...]}
    model            TEXT,                                -- model id that produced the decision
    raw_response     JSONB,                               -- full model JSON, for audit

    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS decisions_site_lead_idx ON decisions (site_id, lead_id, created_at DESC);
CREATE INDEX IF NOT EXISTS decisions_site_time_idx ON decisions (site_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- Sent messages: the STUBBED execution log. Nothing is transmitted.
--   status='skipped' + skip_reason records consent re-checks that blocked a send.
--   sender_type names the stub so a real provider can drop in later.
--   Written by: execution senders (Layer 4).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sent_messages (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id     TEXT   NOT NULL DEFAULT 'default' REFERENCES sites(site_id),
    lead_id     BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    decision_id BIGINT REFERENCES decisions(id) ON DELETE SET NULL,

    channel     TEXT NOT NULL,                            -- email | whatsapp
    sender_type TEXT NOT NULL,                            -- stub_email | stub_whatsapp
    to_address  TEXT,                                     -- email or phone the send targeted
    message     TEXT NOT NULL,
    metadata    JSONB NOT NULL DEFAULT '{}'::jsonb,

    status      TEXT NOT NULL,                            -- sent | skipped
    skip_reason TEXT,                                     -- e.g. consent_revoked, opt_out (when skipped)

    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS sent_site_lead_idx ON sent_messages (site_id, lead_id, created_at DESC);
CREATE INDEX IF NOT EXISTS sent_site_time_idx ON sent_messages (site_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- Optional per-site config overrides (DB-row form of the file config).
--   Files under /config are the source of truth for the prototype; rows here,
--   when present, override file defaults for a given site — the multi-tenant path.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS site_config (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    TEXT NOT NULL DEFAULT 'default' REFERENCES sites(site_id),
    key        TEXT NOT NULL,                             -- page_types | scoring | guardrails | templates
    value      JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (site_id, key)
);

-- ---------------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS leads_set_updated_at ON leads;
CREATE TRIGGER leads_set_updated_at
    BEFORE UPDATE ON leads
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS site_config_set_updated_at ON site_config;
CREATE TRIGGER site_config_set_updated_at
    BEFORE UPDATE ON site_config
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
